# -*- coding: utf-8 -*-
"""Credit Cart Fruad Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEJaZuLOcnsRZH6Ob_QSJ5xXsD2xNF4A
"""

# Install library
!pip install imbalanced-learn

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

# Load dataset
df = pd.read_csv("creditcard.csv")

print("Top 5 rows:")
print(df.head())

# Check NaN in Class column
print("\nNaN count in Class:", df['Class'].isna().sum())

# ❗ FIX – Remove NaN and convert Class to integer
df = df.dropna(subset=['Class'])
df['Class'] = df['Class'].astype(int)

# Check class distribution
print("\nClass distribution after cleaning:")
print(df["Class"].value_counts())

sns.countplot(x=df['Class'])
plt.title("Class Distribution")
plt.show()

# Features and target
X = df.drop("Class", axis=1)
y = df["Class"]

# Normalize Amount column
scaler = StandardScaler()
X['Amount'] = scaler.fit_transform(X[['Amount']])

# Train-test split (stratify = keep class ratio same)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("\nData Split Complete")
print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

# Handle imbalance using SMOTE
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

print("\nBalanced Training Classes:")
print(y_train_res.value_counts())

# ---------------------------
# Logistic Regression
# ---------------------------
lr = LogisticRegression(max_iter=500)
lr.fit(X_train_res, y_train_res)
y_pred_lr = lr.predict(X_test)

print("\n===== Logistic Regression Results =====")
print(classification_report(y_test, y_pred_lr))

# ---------------------------
# Random Forest Model
# ---------------------------
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_res, y_train_res)
y_pred_rf = rf.predict(X_test)

print("\n===== Random Forest Results =====")
print(classification_report(y_test, y_pred_rf))

# Confusion Matrix for RF
cm = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Random Forest")
plt.show()